# Generated by Django 5.0.6 on 2024-05-23 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_blogs_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='blogs',
            name='aid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.author'),
        ),
    ]
