# Generated by Django 5.0.6 on 2024-05-23 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_author_blogs_aid'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='password',
            field=models.CharField(default='defaultpassword', max_length=10),
        ),
    ]
